name: Build Conda Package

on: [ push ]

env:
  OS_INST_FOLDER: empty
  OS_INTERNAL_NAME: empty

jobs:
  build_and_upload:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Conda Build
        run: |
          conda install conda-build
          conda install anaconda
      - name: Build conda
        run: |
          cd conda/
          conda build -c i4ds -c conda-forge .
      - name: Publish to Conda
        if: matrix.os == 'ubuntu-latest'
            ${{ env.OS_INST_FOLDER = 'share' }}
            ${{ env.OS_INTERNAL_NAME = 'linux' }}
        if: matrix.os == 'macos-latest'
            ${{ env.OS_INST_FOLDER = 'local' }}
            ${{ env.OS_INTERNAL_NAME = 'osx' }}
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/${{ env.OS_INST_FOLDER }}/miniconda/conda-bld/${{ env.OS_INTERNAL_NAME }}-64/pfft*.tar.bz2 --force
  install_and_test:
    needs: build_and_upload
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Package
        shell: bash -l {0}
        run: |
          conda activate base
          conda config --append channels conda-forge
          conda install -c i4ds pfft